# Homebrew formula for normfix.
#
# Generated by packaging/render-manifests.sh from the published SHA256SUMS.
# Edit that script, not this file: a release rewrites this one.
class Normfix < Formula
  desc "Safe automatic fixes and clear diagnostics for the 42 Norm"
  homepage "https://normfix.vercel.app"
  version "1.9.1"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/viniciusnevescosta/normfix/releases/download/v1.9.1/normfix-aarch64-macos.tar.gz"
      sha256 "55ae729be753fb7262aac1dc19aafa9671d762a9caacb216cb99a137c927fa37"
    end
    on_intel do
      url "https://github.com/viniciusnevescosta/normfix/releases/download/v1.9.1/normfix-x86_64-macos.tar.gz"
      sha256 "83ab31855865114f2a8883c2d4e419eb2ed0347e7a0e40b1ce61f110ec26c6d4"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/viniciusnevescosta/normfix/releases/download/v1.9.1/normfix-aarch64-linux-gnu.tar.gz"
      sha256 "32ab0fa00b5a087709e4956c4925f3e85c60d0385267afb1a52b191a08eeda40"
    end
    on_intel do
      url "https://github.com/viniciusnevescosta/normfix/releases/download/v1.9.1/normfix-x86_64-linux-gnu.tar.gz"
      sha256 "3e9c45bce8af48cf37ccdfb1a524c4281150623c548414dc1cae806aabb30fc4"
    end
  end

  def install
    bin.install "normfix"
  end

  def caveats
    <<~EOS
      normfix uses the official Norminette, which is not a Homebrew formula.
      Install it by following the instructions in its own repository, which is
      the only source that stays correct when they change:

        https://github.com/42School/norminette

      The tested compatibility baseline is 3.3.59. Another parseable release
      continues with a prominent compatibility advisory; use
      --strict-norminette-version in pinned CI.
      Documentation: https://normfix.vercel.app/docs
    EOS
  end

  test do
    assert_match "normfix #{version}", shell_output("#{bin}/normfix --version")
    assert_match "TOO_MANY_LINES", shell_output("#{bin}/normfix explain TOO_MANY_LINES")
  end
end
