# Homebrew formula for normfix.
#
# Generated by packaging/render-manifests.sh from the published SHA256SUMS.
# Edit that script, not this file: a release rewrites this one.
class Normfix < Formula
  desc "Safe automatic fixes and clear diagnostics for the 42 Norm"
  homepage "https://normfix.vercel.app"
  version "1.9.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/viniciusnevescosta/normfix/releases/download/v1.9.0/normfix-aarch64-macos.tar.gz"
      sha256 "360e39c6c7dbdcc77df39de678d41daec11bcf19fa5bdcd4ace022dcd3439d96"
    end
    on_intel do
      url "https://github.com/viniciusnevescosta/normfix/releases/download/v1.9.0/normfix-x86_64-macos.tar.gz"
      sha256 "b1159c646834f1044f8562e638e28daa5abad99fe6c53c24a23a3aee122d807f"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/viniciusnevescosta/normfix/releases/download/v1.9.0/normfix-aarch64-linux-gnu.tar.gz"
      sha256 "a63260e9e62798f92132706bbb8ada6c7ed8408145c6a8bfa2bc3cb9500f5d78"
    end
    on_intel do
      url "https://github.com/viniciusnevescosta/normfix/releases/download/v1.9.0/normfix-x86_64-linux-gnu.tar.gz"
      sha256 "b1696704ece29c6df0dcbd56d43bd726835016f07a77da61ed72144fe6001e86"
    end
  end

  def install
    bin.install "normfix"
  end

  def caveats
    <<~EOS
      normfix uses the official Norminette, which is not a Homebrew formula.
      Install it by following the instructions in its own repository, which is
      the only source that stays correct when they change:

        https://github.com/42School/norminette

      The tested compatibility baseline is 3.3.59. Another parseable release
      continues with a prominent compatibility advisory; use
      --strict-norminette-version in pinned CI.
      Documentation: https://normfix.vercel.app/docs
    EOS
  end

  test do
    assert_match "normfix #{version}", shell_output("#{bin}/normfix --version")
    assert_match "TOO_MANY_LINES", shell_output("#{bin}/normfix explain TOO_MANY_LINES")
  end
end
