# Homebrew formula for normfix.
#
# Generated by packaging/render-manifests.sh from the published SHA256SUMS.
# Edit that script, not this file: a release rewrites this one.
class Normfix < Formula
  desc "Safe automatic fixes and clear diagnostics for the 42 Norm"
  homepage "https://normfix.vercel.app"
  version "1.8.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/viniciusnevescosta/normfix/releases/download/v1.8.0/normfix-aarch64-macos.tar.gz"
      sha256 "eeef598b60d746e3107d9cdd06404cb727bcc572e1235c84c5a14f29a2984ed7"
    end
    on_intel do
      url "https://github.com/viniciusnevescosta/normfix/releases/download/v1.8.0/normfix-x86_64-macos.tar.gz"
      sha256 "30eca066efeed1c9897f0b1d83a2e32fed900be5d4802bc192f7d9cd713e7ae0"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/viniciusnevescosta/normfix/releases/download/v1.8.0/normfix-aarch64-linux-gnu.tar.gz"
      sha256 "30cbac04b839e9a2ecb56b9621038a150fd781fdfe211ad39fc8df4f684adaff"
    end
    on_intel do
      url "https://github.com/viniciusnevescosta/normfix/releases/download/v1.8.0/normfix-x86_64-linux-gnu.tar.gz"
      sha256 "dbdcdfdc8c440927e5bf125ec5e3412abccd10e548ed71358a570269e71eae84"
    end
  end

  def install
    bin.install "normfix"
  end

  def caveats
    <<~EOS
      normfix uses the official Norminette, which is not a Homebrew formula.
      Install it by following the instructions in its own repository, which is
      the only source that stays correct when they change:

        https://github.com/42School/norminette

      The tested compatibility baseline is 3.3.59. Another parseable release
      continues with a prominent compatibility advisory; use
      --strict-norminette-version in pinned CI.
      Documentation: https://normfix.vercel.app/docs
    EOS
  end

  test do
    assert_match "normfix #{version}", shell_output("#{bin}/normfix --version")
    assert_match "TOO_MANY_LINES", shell_output("#{bin}/normfix explain TOO_MANY_LINES")
  end
end
