#!/bin/sh
# Renders the Homebrew formula and the Scoop manifest from a published release.
#
# Both package managers verify a download against a checksum before installing
# it, which is the point of them here: the checksum is the promise. That promise
# can only be written after the artifacts exist, so hand-editing these files
# always lags a release by one — and it did, leaving the tap on 1.0.0-rc.1 while
# eight releases went out. This script takes the version and the SHA256SUMS the
# release workflow just produced, and writes both files from them.
#
#   packaging/render-manifests.sh 1.8.0 dist/SHA256SUMS .
#
# The output directory holds `Formula/` and `bucket/`, which is where both
# managers look when they are pointed at this repository. Keeping them here
# rather than in two repositories of their own means the release writes them
# with the token it already has, and there is one place to look when an install
# gives somebody the wrong version.
#
# It fails rather than guessing: a missing archive, a missing checksum, or a
# SHA256SUMS naming something it does not recognise stops the run, because a
# manifest with a wrong checksum is worse than no manifest at all.
set -eu

if [ "$#" -ne 3 ]; then
	echo "usage: $0 <version> <sha256sums> <output-directory>" >&2
	exit 2
fi

version="$1"
sums="$2"
output="$3"
repository="https://github.com/viniciusnevescosta/normfix"

if ! awk -v version="$version" 'BEGIN {
	identifier = "[0-9A-Za-z-]+"
	core = "(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)"
	prerelease = "(-" identifier "(\\." identifier ")*)?"
	build = "(\\+" identifier "(\\." identifier ")*)?"
	exit(version ~ ("^" core prerelease build "$") ? 0 : 1)
}'; then
	echo "$0: invalid semantic version \`$version\`" >&2
	exit 1
fi

if [ ! -r "$sums" ]; then
	echo "$0: cannot read checksum manifest \`$sums\`" >&2
	exit 1
fi
mkdir -p "$output/Formula" "$output/bucket"

# Reads one archive's checksum, and refuses to continue without it.
checksum() {
	archive="$1"
	if ! value=$(awk -v name="$archive" '
		$2 == name || $2 == "*" name { value = $1; count++ }
		END {
			if (count != 1) exit 1
			print value
		}
	' "$sums"); then
		echo "$0: \`$sums\` must contain exactly one checksum for \`$archive\`" >&2
		exit 1
	fi
	if [ "${#value}" -ne 64 ]; then
		echo "$0: \`$sums\` has an invalid checksum for \`$archive\`" >&2
		exit 1
	fi
	case "$value" in
		*[!0-9A-Fa-f]*)
			echo "$0: \`$sums\` has an invalid checksum for \`$archive\`" >&2
			exit 1
			;;
	esac
	printf '%s' "$value"
}

macos_arm=$(checksum "normfix-aarch64-macos.tar.gz")
macos_intel=$(checksum "normfix-x86_64-macos.tar.gz")
linux_arm=$(checksum "normfix-aarch64-linux-gnu.tar.gz")
linux_intel=$(checksum "normfix-x86_64-linux-gnu.tar.gz")
windows_intel=$(checksum "normfix-x86_64-windows.zip")
windows_arm=$(checksum "normfix-aarch64-windows.zip")

cat > "$output/Formula/normfix.rb" <<FORMULA
# Homebrew formula for normfix.
#
# Generated by packaging/render-manifests.sh from the published SHA256SUMS.
# Edit that script, not this file: a release rewrites this one.
class Normfix < Formula
  desc "Safe automatic fixes and clear diagnostics for the 42 Norm"
  homepage "https://normfix.vercel.app"
  version "$version"
  license "MIT"

  on_macos do
    on_arm do
      url "$repository/releases/download/v$version/normfix-aarch64-macos.tar.gz"
      sha256 "$macos_arm"
    end
    on_intel do
      url "$repository/releases/download/v$version/normfix-x86_64-macos.tar.gz"
      sha256 "$macos_intel"
    end
  end

  on_linux do
    on_arm do
      url "$repository/releases/download/v$version/normfix-aarch64-linux-gnu.tar.gz"
      sha256 "$linux_arm"
    end
    on_intel do
      url "$repository/releases/download/v$version/normfix-x86_64-linux-gnu.tar.gz"
      sha256 "$linux_intel"
    end
  end

  def install
    bin.install "normfix"
  end

  def caveats
    <<~EOS
      normfix uses the official Norminette, which is not a Homebrew formula.
      Install it by following the instructions in its own repository, which is
      the only source that stays correct when they change:

        https://github.com/42School/norminette

      The tested compatibility baseline is 3.3.59. Another parseable release
      continues with a prominent compatibility advisory; use
      --strict-norminette-version in pinned CI.
      Documentation: https://normfix.vercel.app/docs
    EOS
  end

  test do
    assert_match "normfix #{version}", shell_output("#{bin}/normfix --version")
    assert_match "TOO_MANY_LINES", shell_output("#{bin}/normfix explain TOO_MANY_LINES")
  end
end
FORMULA

cat > "$output/bucket/normfix.json" <<MANIFEST
{
    "version": "$version",
    "description": "Safe automatic fixes and clear diagnostics for the 42 Norm",
    "homepage": "https://normfix.vercel.app",
    "license": "MIT",
    "architecture": {
        "64bit": {
            "url": "$repository/releases/download/v$version/normfix-x86_64-windows.zip",
            "hash": "$windows_intel"
        },
        "arm64": {
            "url": "$repository/releases/download/v$version/normfix-aarch64-windows.zip",
            "hash": "$windows_arm"
        }
    },
    "bin": "normfix.exe",
    "notes": [
        "normfix needs the official Norminette, which Scoop does not install.",
        "Follow https://github.com/42School/norminette; 3.3.59 is the tested baseline.",
        "Documentation: https://normfix.vercel.app/docs"
    ],
    "checkver": {
        "github": "$repository"
    },
    "autoupdate": {
        "architecture": {
            "64bit": {
                "url": "$repository/releases/download/v\$version/normfix-x86_64-windows.zip"
            },
            "arm64": {
                "url": "$repository/releases/download/v\$version/normfix-aarch64-windows.zip"
            }
        },
        "hash": {
            "url": "$repository/releases/download/v\$version/SHA256SUMS"
        }
    }
}
MANIFEST

echo "wrote $output/Formula/normfix.rb and $output/bucket/normfix.json for $version"
